language: php

sudo: false # Use modern Travis builds – http://docs.travis-ci.com/user/migrating-from-legacy/

git:
  depth: 1

services:
  - mysql

matrix:
  include:
    # current stable release w/ multisite
    - php: "5.6"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "7.2"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "7.3"
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: "7.4"
      env: WP_VERSION=latest WP_MULTISITE=0
    # n-1 major release
    - php: "5.6"
      env: WP_VERSION=5.2.5 WP_MULTISITE=0
    - php: "7.0"
      env: WP_VERSION=5.2.5 WP_MULTISITE=0
    - php: "7.2"
      env: WP_VERSION=5.2.5 WP_MULTISITE=0
    - php: "7.3"
      env: WP_VERSION=5.2.5 WP_MULTISITE=0
    # - skip PHP 7.4 and WP 5.2 (not compatible)

before_script:
  - export PHPCS_DIR=/tmp/phpcs
  - export SNIFFS_DIR=/tmp/sniffs
  - |
    if [[ "$SNIFF" == "1" ]]; then
      # Install CodeSniffer for WordPress Coding Standards checks.
      wget -O $PHPCS_DIR/phpcs https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      chmod +x $PHPCS_DIR/phpcs
      # Install WordPress Coding Standards.
      git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR
      # Install WordPress VIP Coding Standards.
      git clone -b master --depth 1 https://github.com/Automattic/VIP-Coding-Standards.git $SNIFFS_DIR
      # Install PHP Compatibility sniffs.
      git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
      # Set install path for PHPCS sniffs.
      $PHPCS_DIR/phpcs --config-set installed_paths $SNIFFS_DIR
      # After CodeSniffer install you should refresh your path.
      phpenv rehash
    fi
  - |
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$PHPCS_DIR:$PATH"
script:
  # Search for PHP syntax errors.
  - find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # WordPress Coding Standards.
  - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=WordPress-VIP-Go,WordPress --ignore=tests; fi
  - phpunit